env:
    browser: true
    es6: true
extends:
    - plugin:react/recommended
    - airbnb
    - plugin:prettier/recommended
    - prettier/react
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures: { jsx: true }
    ecmaVersion: 2020
    sourceType: module
plugins:
    - react
rules:
    import/extensions: [error, ignorePackages]
    import/no-extraneous-dependencies: [error, { packageDir: '.' }]
    react/prop-types: off
    jsx-a11y/label-has-associated-control: off
